version: '3'
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        volumes:
            - ./frontend:/app/
        ports:
            - '3000:3000'
        restart: on-failure
        container_name: frontend
        stdin_open: true

    backend:
        build:
            context: ./backend
        image: backend
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - ./backend:/app/app
        environment:
            - FLASK_ENV=development