version: '3.8'
services:
  backend:
    build:
      context: .
      network: host
    image: backend
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development